# Generated by Django 4.1.7 on 2023-03-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('badge_1', models.CharField(blank=True, max_length=20, verbose_name='badge_1')),
                ('badge_2', models.CharField(blank=True, max_length=20, verbose_name='badge_2')),
                ('kayq_1', models.CharField(blank=True, max_length=20, verbose_name='kayq_')),
                ('kayq_1_link', models.CharField(blank=True, max_length=50, verbose_name='kayq_1_link')),
                ('kayq_2', models.CharField(blank=True, max_length=20, verbose_name='kayq_2')),
                ('kayq_2_link', models.CharField(blank=True, max_length=50, verbose_name='kayq_2_link')),
                ('kayq_3', models.CharField(blank=True, max_length=20, verbose_name='kayq_3')),
                ('kayq_3_link', models.CharField(blank=True, max_length=50, verbose_name='kayq_3_link')),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
            },
        ),
    ]
