# Generated by Django 4.1.7 on 2023-03-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='img',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Image'),
        ),
    ]
