# Generated by Django 4.1.7 on 2023-03-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hero_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='verification',
            field=models.BooleanField(null=True, verbose_name='Yes/No'),
        ),
    ]
