# Generated by Django 4.1.7 on 2023-03-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50, verbose_name='Home info name1')),
                ('name2', models.CharField(max_length=50, verbose_name='Home info name2')),
                ('button_name', models.CharField(max_length=50, verbose_name='Home button')),
            ],
        ),
        migrations.CreateModel(
            name='HomeLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images', verbose_name='Home logo')),
            ],
        ),
    ]
