# Generated by Django 4.1.7 on 2023-03-29 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_homeinfo_homelogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Last_episode name')),
                ('img', models.ImageField(null=True, upload_to='images', verbose_name='Last_episode image')),
                ('text', models.TextField(verbose_name='Description')),
                ('minute', models.CharField(max_length=50, verbose_name='Minutes')),
                ('episode', models.IntegerField(verbose_name='Episodes')),
                ('listen', models.CharField(max_length=10, verbose_name='Listen')),
                ('like', models.CharField(max_length=10, verbose_name='Like')),
                ('comment', models.CharField(max_length=10, verbose_name='Comment')),
                ('download', models.CharField(max_length=10, verbose_name='Download')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_episode', to='main.hero')),
            ],
        ),
    ]
