# Generated by Django 4.1.7 on 2023-03-29 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_trendepisode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_episode', to='main.hero')),
            ],
        ),
    ]
