# Generated by Django 4.1.7 on 2023-03-29 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_trendepisode'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendepisode',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trend_episode_info', to='main.lastepisode'),
        ),
        migrations.AlterField(
            model_name='trendepisode',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_episode_author', to='main.hero'),
        ),
    ]
