# Generated by Django 4.1.7 on 2023-03-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_trendepisode_info_alter_trendepisode_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.ImageField(blank=True, upload_to='images', verbose_name='Header Image')),
                ('banner', models.ImageField(blank=True, upload_to='images', verbose_name='Banner Image')),
                ('footer', models.ImageField(blank=True, upload_to='images', verbose_name='Footer Image')),
            ],
        ),
    ]
