# Generated by Django 4.1.7 on 2023-03-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_bgimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='kayq_1_link',
            field=models.URLField(blank=True, max_length=50, verbose_name='kayq_1_link'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='kayq_2_link',
            field=models.URLField(blank=True, max_length=50, verbose_name='kayq_2_link'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='kayq_3_link',
            field=models.URLField(blank=True, max_length=50, verbose_name='kayq_3_link'),
        ),
    ]
