# Generated by Django 4.1.7 on 2023-03-29 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_hero_kayq_1_link_alter_hero_kayq_2_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourstory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_hero', to='main.hero')),
            ],
        ),
    ]
