# Generated by Django 4.1.7 on 2023-03-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_ourstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='About Pod image')),
                ('text', models.TextField(verbose_name='Text')),
            ],
        ),
        migrations.AlterModelOptions(
            name='ourstory',
            options={'verbose_name': 'Ourstory', 'verbose_name_plural': 'Ourstories'},
        ),
    ]
